In [1]:
import numpy as np

In [3]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a = np.arange(3)
a
a.shape

(3,)

In [5]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [9]:
a = np.arange(3).reshape((3,1))
a
a.shape

(3, 1)

In [10]:
b = np.arange(3)
b
b.shape

(3,)

In [11]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [12]:
x = np.random.random((10,3))
x

array([[0.76762192, 0.10273798, 0.61742835],
       [0.3536017 , 0.37986416, 0.88926514],
       [0.25007602, 0.23926672, 0.51818328],
       [0.83542748, 0.16913695, 0.94917165],
       [0.07040141, 0.31897223, 0.53720765],
       [0.81553387, 0.21914248, 0.86840897],
       [0.77308938, 0.55445978, 0.44433121],
       [0.27482468, 0.4439771 , 0.25140772],
       [0.2597198 , 0.72773935, 0.84464507],
       [0.51310414, 0.98189781, 0.93858977]])

In [13]:
xmean = x.mean(0)
xmean

array([0.49134004, 0.41371946, 0.68586388])

In [14]:
x_centered = x - xmean
x_centered

array([[ 0.27628188, -0.31098148, -0.06843553],
       [-0.13773834, -0.0338553 ,  0.20340126],
       [-0.24126402, -0.17445274, -0.1676806 ],
       [ 0.34408744, -0.24458251,  0.26330777],
       [-0.42093863, -0.09474722, -0.14865623],
       [ 0.32419383, -0.19457697,  0.18254509],
       [ 0.28174934,  0.14074033, -0.24153267],
       [-0.21651536,  0.03025764, -0.43445616],
       [-0.23162024,  0.3140199 ,  0.15878119],
       [ 0.0217641 ,  0.56817835,  0.25272589]])

In [16]:
x_centered.mean(0)

array([-1.11022302e-16, -4.44089210e-17,  2.22044605e-17])